run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck
    - misspell
    - revive
    - gocyclo
    - dupl
    - gosec
    - unconvert

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  misspell:
    locale: US
  revive:
    rules:
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false

issues:
  exclude-rules:
    # Exclude dupl and gocyclo for test files
    - path: _test\.go
      linters:
        - dupl
        - gocyclo
        - gosec
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"
    # Exclude linters for generated files
    - path: \.pb\.go
      linters:
        - all

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
